name: CI-CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Copy files
        uses: actions/checkout@v3

      - name: Install dependecies and execute tests in docker compose
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: docker-compose.yml
          service: app
          command: composer install && composer pest
  
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true